name: Build OpenSearch from source and run tests

env:
  VERSION: 2.3.0
  RELEASE: edge
  BRANCH: ${{ github.ref_name }}

on:
  push:
    branches:
      - "*"

jobs:
  build:
    name: Build Snap
    runs-on: ubuntu-latest
    outputs:
      snap-file: ${{ steps.build-snap.outputs.snap }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH }}

      - id: check-code
        name: Perform CI checks
        run:
          make checks

      - id: build-snap
        name: Build snap
        uses: snapcore/action-build@v1
        with:
          snapcraft-channel: 7.x/candidate

      - name: Upload built snap job artifact
        uses: actions/upload-artifact@v3
        with:
          name: opensearch_snap_amd64
          path: opensearch_${{env.VERSION}}_amd64.snap

  test:
    name: Test Snap
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download snap file
        uses: actions/download-artifact@v3
        with:
          name: opensearch_snap_amd64
          path: .

      - name: Install snap file
        run: |
          sudo snap install opensearch_${{env.VERSION}}_amd64.snap --dangerous

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH }}

      - name: Run Integration Tests
        run: |
          
          make integration-tests

  publish:
    name: publish
    if: needs.build-condition.outputs.decision  ==  '1' && github.ref_name == 'main'
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Download snap file
        uses: actions/download-artifact@v3
        with:
          name: opensearch_snap_amd64
          path: .

      - name: Publish snap to Store
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          snap: opensearch_${{env.VERSION}}_amd64.snap
          release: ${{env.RELEASE}}
